name: "Maven Release"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Create .ssh directory
      run: md C:\Users\runneradmin\.ssh
    - name: Create known hosts file
      run: |
        echo github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl > C:\Users\runneradmin\.ssh\known_hosts
        echo. >> C:\Users\runneradmin\.ssh\known_hosts
    - name: Create private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > C:\Users\runneradmin\.ssh\id_ed25519
    - name: SSH Git clone
      run: git clone ssh://git@github.com/nbauma109/jd-gui-duo.git
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create maven settings
      uses: s4u/maven-settings-action@v2.5.0
      with:
        servers: '[{"id": "github.com", "username": "git", "privateKey": "C:/Users/runneradmin/.ssh/id_ed25519"}]'
    - name: Git Config
      run: |
        git config --global user.email "git@github.com"
        git config --global user.name "git"
    - name: Release with Maven
      run: |
        cd jd-gui-duo
        mvn -B -Dusername=git release:clean release:prepare release:perform
    - name: Delete key
      run: DEL /F /Q C:\Users\runneradmin\.ssh\id_ed25519
