name: "Maven Release"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Display env
      run: "dir env:"
    - name: Display settings
      run: type %USERPROFILE%\.m2\settings.xml
    - name: Git Config
      run: |
        git config --global user.email "git@github.com"
        git config --global user.name "git"
    - name: Release with Maven
      run: mvn -B release:clean release:prepare release:perform
