name: "Maven Release"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create maven settings
      uses: s4u/maven-settings-action@v2.5.0
      with:
        servers: '[{"id": "github", "username": "git", "privateKey": "${{ secrets.SSH_PRIVATE_KEY }}", "filePermissions": "664", "directoryPermissions": "775"}]'
    - name: Release with Maven
      run: mvn -B -Dusername=git release:clean release:prepare release:perform
