name: "Maven Release"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > C:\Users\RUNNER~1\AppData\Local\Temp\sshkey
    - name: Create maven settings
      uses: s4u/maven-settings-action@v2.5.0
      with:
        servers: '[{"id": "githubssh", "username": "git", "privateKey": "C:/Users/RUNNER~1/AppData/Local/Temp/sshkey"}]'
    - name: Git Config
      run: |
        git config --global user.email "git@github.com"
        git config --global user.name "git"
    - name: Release with Maven
      run: mvn -B -Dusername=git release:clean release:prepare release:perform
    - name: Delete key
      run: DEL /F /Q C:\Users\RUNNER~1\AppData\Local\Temp\sshkey
