name: "Maven Release"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"

    steps:
    - name: Install packages
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get -y update
        sudo apt-get -y install dos2unix libz1:i386 libncurses5:i386 libbz2-1.0:i386
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk/
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
